routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\site\CartContoller;
use App\Http\Controllers\site\HomeController;
use App\Http\Middleware\OnlyAdmin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[HomeController::class,'index']);
Route::get('/electronics',[HomeController::class,'electronics']);
Route::get('/item/{id}',[HomeController::class,'product']);
Route::post('/add_product/{id}',[CartContoller::class,'cart_add']);
// Route::post('/add_product/colour',[CartContoller::class,'store']);
Route::get('/checkout',[CartContoller::class,'checkout']);
Route::get('/cart/cart_remove_one_product/{id}',[CartContoller::class,'cart_remove_one_product']);
Route::get('/cart/cart_add_one_product/{id}',[CartContoller::class,'cart_add_one_product']);
Route::get('/cart/remove/{id}',[CartContoller::class,'cart_remove']);


// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::prefix('/admin')->middleware(['auth',OnlyAdmin::class/*,'verified'*/])->group(function () {
    Route::get('/dashboard',[DashboardController::class,'index'])->name('admin.dashboard');
   Route::resource('/categories',CategoryController::class);
   Route::resource('/products',ProductController::class);
});


require __DIR__.'/auth.php';
 

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function images()
    {
        return $this->hasMany(Image::class);
    }

    public function selected_size()
    {
        return $this->hasOne(Selected_size::class);
    }

    public function selected__colour()
    {
        return $this->hasOne(Selected_Colour::class);
    }

    public function selected_quantity()
    {
        return $this->hasOne(Selected_quantity::class);
    }


    public function getPriceAfterDiscountAttribute()
    {
        return $this->price - $this->discount_amount;
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Interfaces\ICategoryRepository;
use App\Interfaces\IProductRepository;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    protected $productRepo;
    protected $categoryRepo;

    public function __construct(IProductRepository $productRepo,ICategoryRepository $categoryRepo)
    {
        $this->productRepo = $productRepo;
        $this->categoryRepo = $categoryRepo;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product=$this->productRepo->get();
        $data['product']=$product;
        return view('admin.product.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['categories']=$this->categoryRepo->get();
        return view('admin.product.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $this->productRepo->CreateProduct($request);
        return redirect('/admin/products');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layouts.app')

@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Product</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Product</li>
    </ol>
  </div>
</div>
@endsection

@section('content')
<div class="card"> 
    <div class="card-header">
      <h3 class="card-title">Add Product</h3>
    </div>
    <div class="card-body">
        <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
              <div class="form-group">
                <label for="exampleInputEmail1">Product Name</label>
                <input type="text" class="form-control" name="name" id="category" value="{{ old('name') }}" placeholder="Enter product Name">
              </div>
              @error('name')
              <p class="text-danger">{{ $message }}</p>
              @enderror

              <div class="form-group">
                <label for="exampleInputEmail1">Category</label>
                <select name="category_id" class="form-control">
                  @foreach ($categories as $item)
                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                  @endforeach
                </select>
              </div>
              @error('name')
              <p class="text-danger">{{ $message }}</p>
              @enderror

              <div class="form-group">
                <label for="exampleInputEmail1">Product Price</label>
                <input type="number" class="form-control" name="price" value="{{ old('price') }}" placeholder="Enter product price">
              </div>
              @error('price')
              <p class="text-danger">{{ $message }}</p>
              @enderror

            <div class="form-group">
                <label for="exampleInputEmail1">Discount Amount</label>
                <input type="text" class="form-control" name="discount_amount" value="{{ old('discount_amount') }}" placeholder="Enter Discount Amount">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Remaining Stock</label>
                <input type="text" class="form-control" name="stock" value="{{ old('stock') }}" placeholder="Enter Product Stock">
            </div>
            
            <div class="form-group">
                <label for="exampleInputEmail1">Description</label>
               <textarea name="description" class="form-control">{{ old('description') }}</textarea>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Product Size</label>
              <input type="text" class="form-control" name="size" id="size" value="{{ old('size') }}" placeholder="Enter product sizes">
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1">Product Colour</label>
              <input type="text" class="form-control" name="colour" id="colour" value="{{ old('colour') }}" placeholder="Enter product colour">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Featured Image</label>
                <input type="file" name="featured_image">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Images</label>
                <input type="file" name="images[]" multiple>
            </div>
    </div>
         
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </form>
</div>

@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layouts.app')

@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Products</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Products</li>
    </ol>
  </div>
</div>
@endsection

@section('content')
<div class="card">
    <div class="card-header">
      <h3 class="card-title">Product List</h3>
      <div class="card-tools">
        <a  class="btn btn-success" href="{{ url('/admin/products/create') }}">Add New Product</a>
      </div>
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Category</th>
            <th>Name</th>
            <th>Price</th>
            <th>Discount Amount</th>
            <th>Featured Image</th>
            <th>Stock</th>
            <th>Sizes</th>
            <th>Colours</th>
            <th>Description</th>
            <th>Action</th>
            
          </tr>
        </thead>
        <tbody>
         
          
            @foreach ($product as $item)
            <tr>
                <td>{{ $item->category->name }}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->price }}</td>
                <td>{{ $item->discount_amount }}</td>
                <td><img src="{{ asset("storage/$item->featured_image") }}" width="100px"></td>
                <td>{{ $item->stock }}</td>
                @php
                $size=$item->size;
                $product_size=explode(',',$size);
                @endphp
                <td>
                  @foreach ($product_size as $one_size)
                      {{ $one_size }}<br>
                  @endforeach
                </td>
                @php
                $colour=$item->colour;
                $product_colour=explode(',',$colour);
                @endphp
                <td>
                  @foreach ($product_colour as $one_colour)
                      {{ $one_colour }}<br>
                  @endforeach
                </td>
                <td>{{ $item->description }}</td>
                
                <td>
                  <div class="btn-group" role="group">
                    <a href="{{ url("admin/categories/$item->id/edit") }}" class="btn btn-primary btn-sm">Update</a>
                   
    
                    <form action="{{ url("/admin/categories/$item->id") }}" method="POST" onsubmit="return confirm('Do you really want to delete this category?');">
                        @csrf
                        @method('delete')
                        <input type="submit" value="Delete" class="btn btn-danger btn-sm ml-1">
                    </form>
                  </div>
                </td>
              </tr>
            @endforeach 
        </tbody>
      </table>
    </div>
   
    
  </div>
@endsection