routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\site\CartContoller;
use App\Http\Controllers\site\HomeController;
use App\Http\Middleware\OnlyAdmin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[HomeController::class,'index']);
Route::get('/electronics',[HomeController::class,'electronics']);
Route::get('/item/{id}',[HomeController::class,'product']);
Route::post('/add_product/{id}',[CartContoller::class,'cart_add']);
// Route::post('/add_product/colour',[CartContoller::class,'store']);
Route::get('/checkout',[CartContoller::class,'checkout']);
Route::get('/cart/cart_remove_one_product/{id}',[CartContoller::class,'cart_remove_one_product']);
Route::get('/cart/cart_add_one_product/{id}',[CartContoller::class,'cart_add_one_product']);
Route::get('/cart/remove/{id}',[CartContoller::class,'cart_remove']);


// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::prefix('/admin')->middleware(['auth',OnlyAdmin::class/*,'verified'*/])->group(function () {
    Route::get('/dashboard',[DashboardController::class,'index'])->name('admin.dashboard');
   Route::resource('/categories',CategoryController::class);
   Route::resource('/products',ProductController::class);
});


require __DIR__.'/auth.php';
 

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\Enums\MainCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\CategoryRequest;
use App\Interfaces\ICategoryRepository;

class CategoryController extends Controller
{
    protected $categoryRepo;

    public function __construct(ICategoryRepository $categoryRepo)
    {
        $this->categoryRepo = $categoryRepo;
    } 


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category=$this->categoryRepo->get();
        $data['category_list']=$category;
        return view('admin.categories.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data["main_category"]=MainCategory::asSelectArray();
        return view('admin.categories.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $this->categoryRepo->createCategory($request);
        return redirect('/admin/categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category=$this->categoryRepo->find($id);
        if(!$category)
        {
            return redirect('/admin/categories');
        }
        $data["category"]=$category;
        $data["main_category"]=MainCategory::asSelectArray();
        return view('admin.categories.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //$category=$this->categoryRepo->find($id);
        $this->categoryRepo->UpdateCategory($request, $id);
        return redirect('/admin/categories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->categoryRepo->delete($id);
        return redirect('/admin/categories');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Category</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Category</li>
    </ol>
  </div>
</div>
@endsection

@section('content')
<div class="card"> 
    <div class="card-header">
      <h3 class="card-title">Add Category</h3>
    </div>
    <div class="card-body">
        <form action="{{ route('categories.store') }}" method="POST">
            @csrf
            <div class="card-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Main Category</label>
                <select name="main_category_id"  class="form-control">
                    @foreach ($main_category as $key => $item)
                        <option value="{{ $key }}" {{ old('main_category_id')==strval($key) ? 'selected':''}}>{{ $item  }}</option>
                    @endforeach
                </select>
              </div>
              @error('name')
              <p class="text-danger">{{ $message }}</p>
          @enderror
              <div class="form-group">
                <label for="exampleInputEmail1">Category Name</label>
                <input type="text" class="form-control" name="name" id="category" value="{{ old('name') }}" placeholder="Enter Category Name">
              </div>
              @error('name')
              <p class="text-danger">{{ $message }}</p>
          @enderror
            </div>
         
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </form>
    </div>
   
    
  </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Category</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Category</li>
    </ol>
  </div>
</div>
@endsection

@section('content')
<div class="card"> 
    <div class="card-header">
      <h3 class="card-title">Update Category</h3>
    </div>
    <div class="card-body">
        <form action="{{ url("/admin/categories/$category->id") }}" method="POST">
          @method("put")
          @csrf
            <div class="card-body"> 
              <div class="form-group">
                <label for="exampleInputEmail1">Main Category</label>
                <select name="main_category_id"  class="form-control">
                    @foreach ($main_category as $x =>$main_category_id)
                    <option value="{{ $x }}" {{ $category->main_category_id==strval($x) ? 'selected':''}}>{{ $main_category_id }}</option>
                @endforeach
                </select>
              </div>
              @error('name')
              <p class="text-danger">{{ $message }}</p>
          @enderror
              <div class="form-group">
                <label for="exampleInputEmail1">Category Name</label>
                <input type="text" class="form-control" name="name" id="category" value="{{ $category->name }}" placeholder="Enter Category Name">
              </div>
              @error('name')
              <p class="text-danger">{{ $message }}</p>
          @enderror
            </div>
         
            <!-- /.card-body -->

            <div class="card-footer">
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
          </form>
    </div>
   
    
  </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')


@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Category</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Category</li>
    </ol>
  </div>
</div>
@endsection

@section('content')
<div class="card">
    <div class="card-header">
      <h3 class="card-title">Category List</h3>
      <div class="card-tools">
        <a  class="btn btn-success" href="{{ url('/admin/categories/create') }}">Add New Category</a>
      </div>
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Main Category</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
            @foreach ($category_list as $item)
            <tr>
                <td>{{ $item->name }}</td>
                <td>{{ App\Enums\MainCategory::getDescription($item->main_category_id) }}</td>
                <td>
                  <div class="btn-group" role="group">
                    <a href="{{ url("admin/categories/$item->id/edit") }}" class="btn btn-primary btn-sm">Update</a>
                    {{-- <a href="" class="btn btn-danger btn-sm">Delete</a> --}}
    
                    <form action="{{ url("/admin/categories/$item->id") }}" method="POST" onsubmit="return confirm('Do you really want to delete this category?');">
                        @csrf
                        @method('delete')
                        <input type="submit" value="Delete" class="btn btn-danger btn-sm ml-1">
                    </form>
                  </div>
                </td>
              </tr>
            @endforeach 
        </tbody>
      </table>
    </div>
   
    
  </div>
@endsection